---
remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Edward Vanderwall's Extracurricular Portfolio
#description: [This page serves as a showcase of my efforts past my undergraduate work.
 #This includes some expanded-upon work projects done while working for the University of Minnesota's Office of Sustainability as well as work
  #done simply for personal interests.]
---
